server:
  max-http-request-header-size: 2MB
  servlet:
    context-path: /v1/user-service
  port: 8091

spring:
  application:
    name: nagp-demo-user-service
  #profiles:
  #  active: dev # can be overridden by env var SPRING_PROFILES_ACTIVE
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: testDBPool

  jpa:
    #hibernate:
    #  ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        format_sql: true
      default_schema: ${DB_SCHEMA}
      hibernate.order_by.default_null_ordering: last
  flyway:
    baseline-on-migrate: true
    schemas[]: ${DB_SCHEMA}
    default-schema: ${DB_SCHEMA}
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

x-api-key:
  value: ${X_API_KEY}
