CREATE TABLE IF NOT EXISTS users (
	id int8 NOT NULL GENERATED ALWAYS AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
	"name" varchar(100) NULL,
	email varchar(200) NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id)
);